### ISSUE TITLE
Truth Tables are wrong

### ISSUE THREAD

**Issue by JakeyGilly** [HenryDewsnap/LogicGateSim#1]
![image](https://user-images.githubusercontent.com/57807696/146422785-16ad265c-b510-474b-b851-3bf8269f80a6.png)
Truth tables are ment to go
```
0 0
0 1
1 0
1 1
```
according to welsh electronics
like counting up in binary

**Comment by HenryDewsnap** [comment]
dealt with, thanks for bringing this up.
